name: dreambook_deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_version:
    name: check flutter version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'
          channel: 'stable'
      - run: flutter --version
